repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Pyright for type checking
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run --frozen pyright
        language: system
        types: [python]
        require_serial: true

  # Cyclomatic Complexity check with lizard
  - repo: local
    hooks:
      - id: lizard
        name: lizard (CCN check)
        entry: uv run --frozen lizard src --CCN 10
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

  # Pytest for running tests
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run --frozen pytest
        language: system
        pass_filenames: false
        always_run: true

  # File length check
  - repo: local
    hooks:
      - id: file-length-check
        name: file length check (max 600 lines)
        entry: python scripts/check_file_length.py
        language: system
        types: [python]
        pass_filenames: true

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
