name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Run ruff linting
      run: uv run --frozen ruff check .

    - name: Run ruff formatting check
      run: uv run --frozen ruff format --check .

    - name: Run pyright type checking
      run: uv run --frozen pyright

    - name: Run tests with coverage
      run: uv run --frozen pytest --cov=src --cov-report=xml --cov-report=term-missing

    - name: Check code complexity
      run: uv run lizard src/tcc_analyzer --CCN 10

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  build-test:
    name: Test executable build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: test  # Wait for test job to complete
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.10

    - name: Install dependencies
      run: uv sync --dev

    - name: Test executable build
      run: |
        uv run python scripts/build-executable.py --platform ${{ matrix.platform }}

    - name: Test executable functionality
      shell: bash
      run: |
        if [[ "${{ matrix.platform }}" == "windows" ]]; then
          ./dist/tcc-analyzer.exe --version
          ./dist/tcc-analyzer.exe --help
        else
          ./dist/tcc-analyzer --version
          ./dist/tcc-analyzer --help
        fi

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: tcc-analyzer-${{ matrix.platform }}-dev
        path: dist/tcc-analyzer*
        retention-days: 3
